CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package-lock.json
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package-lock.json
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package-lock.json
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package-lock.json
packages/iguazu-holocron/package.json

Version bump. Please see changelogs.
I will squash to commit message: `chore(release): 1.1.0`

Holocron v1.1.0

---

packages/holocron-module-route/README.md
packages/holocron/API.md
packages/holocron/README.md

* Add One Doc ID Blocks to Holocron API

Add One Doc ID Blocks to Holocron API

---

.github/labeler.yml
.github/workflows/labeler.yml
package-lock.json
package.json

Adds https://github.com/actions/labeler to add labels to help organize PRs better.

chore(workflows): add labeler GitHub action

---

packages/iguazu-holocron/package-lock.json
packages/iguazu-holocron/package.json

Just updating the version to not use a pre-release version of iguazu.

chore(iguazuHolocron): update iguazu to an official version

---

.github/workflows/tests.yml
.travis.yml
CONTRIBUTING.md
README.md
lerna.json
package.json
packages/holocron-module-register-webpack-plugin/README.md
packages/holocron-module-route/README.md
packages/holocron-module-route/src/ducks/moduleRoutePrefetch.js
packages/holocron/README.md
packages/iguazu-holocron/README.md

refactor(main): rename

---

.github/workflows/health-check.yml

Adding health check to the workflows on main branch

chore(workflow): add health check

---

.github/workflows/release.yml

Check it out working here https://github.com/nellyk/holocron/actions/runs/257779730

release actions fix

---

CONTRIBUTING.md

docs(contributing): update release section

---

.github/pull_request_template.md

Fixes #58 
Added a Pull Request Template

docs(pull-request-template): add a pull request template

---

README.md

Added learna.js badge to docs.
Added learna.js badge to give credit/spread repo awareness.
Helps spread repo awareness for lerna.js and the GitHub community.
This has no impact on developers currently using holocron.

docs: Added lerna.js badge

---

packages/holocron-module-route/__tests__/ModuleRouteUtils.spec.jsx
packages/holocron-module-route/src/ModuleRouteUtils.jsx

Rejected promises were not being returned which meant that they would fail and cause the App to crash
americanexpress/one-app#213
locally and unit tests

fix(moduleRoute): return promises

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

Version bump to 1.1.3
new version available

Version v1.1.3

---

yarn.lock

chore(yarn-lock): add missing dependency update

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

This reverts commit 403c1978ae4595ddc8333f13ef2affd0b3f5cb70.

Revert "chore(release): 1.1.3"

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

chore(release): 1.1.3

---

packages/holocron/docs/api/README.md

Updating `RenderModule` documentation

docs(rendermodule): remove holocronModule import

---

packages/holocron-module-route/__tests__/ModuleRouteUtils.spec.jsx
packages/holocron-module-route/src/ModuleRouteUtils.jsx

When updating One App's version of Holocron Module Route to 1.1.3, there were some strange errors highlighted by the integration tests. These occurred as One App Router will call the provided callback again if a promise is returned from the moduleRoute routing functions. https://github.com/americanexpress/one-app-router/blob/main/modules/matchRoutes.js#L56
This fix ensures that errors thrown during the updated functions can be handled by the callback chain within One App Router's `matchRoutes` while also not invoking the callback an additional time.
https://github.com/americanexpress/one-app/issues/213
Failing edge cases caused by previous fix have been replicated and fixed by this update locally.
Tests have been updated to ensure that any errors thrown during the `then` will be handled …

fix(moduleRoute): correctly catch route props errors

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

chore(release): 1.1.4

---

.github/workflows/release.yml
.github/workflows/tests.yml

Fixes commit-lint on CI as it was ignoring bad commit messages

fix(commitlint): validate commit message on ci

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

chore(release): 1.1.5

---

packages/holocron/__tests__/__snapshots__/updateModuleRegistry.spec.js.snap
packages/holocron/__tests__/updateModuleRegistry.spec.js
packages/holocron/src/updateModuleRegistry.js
yarn.lock

A child module that requires an external that is NOT provided by its root module will cause one-app to fail to start up, or fail polling if already running.
This fix works by catching an error that is thrown by `onModuleLoad`, a function passed to holocron from the one-app server. Typically this error would bubble up to one-app, where the module map polling would fail. 
By catching the error, we are able to ignore the "bad" module by preventing it from being updated in the in-memory module map.
This means that if an existing module is updated to require an external that is NOT provided by the parent, we will use its last stable version until a working version of that module is deployed.
This does not affect the module map polling. It will continue to climb as normal up to the …

fix(externals): mismatched externals caused one-app to fail to start

---

packages/holocron/__tests__/__snapshots__/holocronModule.spec.jsx.snap
packages/holocron/__tests__/holocronModule.spec.jsx
packages/holocron/src/holocronModule.jsx

Removed UNSAFE lifecycle method. 
This change is to update legacy/ UNSAFE method with newer lifecycle hook provided by react. 
Tested running one-app locally with changes made in holocron.
It should not impact. This is refactoring and does not change behavior of code.

refactor(lifecyleMethod): refactor holocron UNSAFE lifecyle

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

This release includes a fix for Externals.

chore(release): 1.2.0

---

packages/holocron/__tests__/updateModuleRegistry.spec.js
packages/holocron/src/updateModuleRegistry.js

the `flatModuleMap` array wasn't being updated to remove modules with issues. This allowed for the possibility of the bad module still being updated because of bad indexing.
This fixes the issue described above
Unit test

fix(updateModuleRegistry): flatModuleMap contained problem modules

---

CHANGELOG.md
lerna.json
packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json
packages/iguazu-holocron/CHANGELOG.md
packages/iguazu-holocron/package.json

Adds a fix for holocron to prevent bad modules from being put in the module map

chore(release): 1.2.1

---

.github/workflows/publish.yml
lerna.json

add workflow to manually publish

chore(publish): create workflow

---

.github/labeler.yml

changes made to labeler.yml 
```
one-app-team-review-requested:
- '**/*'
```
proper file globing so that all files with a change will cause the label to be added to the pr
previously, the labeler work flow would only append the ```one-app-team-review-requested``` to any pr with a change to the root of the repository and not any other sub directories. 
forked Holocron to set up actions and change actions.

fix(labeler-workflow): proper globbing

---

packages/holocron-module-register-webpack-plugin/HolocronModuleRegisterPlugin.js
packages/holocron-module-register-webpack-plugin/__tests__/HolocronModuleRegisterPlugin.spec.js

Fixed lazy loading issue by adding hyphenated module name to fix web-pack chunk filename clashing.
Added hyphenated module name instead of static `holocronModule` in `HolocronModuleRegisterPlugin`
This solves chunk filename clashing while using react lazy load.
Yes. This is tested with production application, which has lazy loading issue. It has been tested with application, without lazy load to verify current changes still works in both cases. 
- [ X] Bug fix (non-breaking change which fixes an issue)
Developers can happily use react lazy load.

fix(lazy-loading): fixed webpack filename clashing issue

---

.github/workflows/publish.yml

Publish action missing git author

chore(action): publish include git author

---

packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/package.json
packages/holocron/package.json
packages/iguazu-holocron/package.json

chore(package): remove deadname

---

packages/holocron/docs/api/README.md

docs(api): fix mapStateToProps args list

---

packages/holocron/__tests__/updateModuleRegistry.spec.js
packages/holocron/docs/api/README.md
packages/holocron/src/updateModuleRegistry.js

Enable option to have `updateModuleRegistry` list the rejected modules enabling consumers of function to change logic based on success of modules updates. 
Historically this could have been done based on `updateModuleRegistry` throwing error if any module rejected.
Enable more choices based on `rejectedModules`
Test suite, locally.
They will need to opt into getting new response shape.

feat(updateModuleRegistry): allow rejected modules to be listed

---

.github/workflows/health-check.yml
.github/workflows/tests.yml
package.json
packages/holocron-module-register-webpack-plugin/__tests__/HolocronModuleRegisterPlugin.spec.js

Drop support for node 10 and 12. Considering this as NOT BREAKING as Node 10 and 12 reached EOL
use node versions 14.x, 16.x, 18.x for actions workflows.
node 10 and 12 are EOL.
locally and by this pr..

chore(node): drop versions 10 and 12 as EOL

---

packages/holocron/__tests__/externalRegistry.spec.jsx
packages/holocron/src/externalRegistry.js

Limits the chance of external registries from having `undefined` entries
Also included JSdoc declarations for external registry 
fixes bug when integrated with One App. 
unit tests, tested locally by installing in to one-app server and running one-apps integration test suite. integration tests failed before changes and succeed after.

fix(externalRegistry): prevent undefined entries

---

packages/holocron/__tests__/loadModule.node.spec.js
packages/holocron/src/loadModule.node.js

Is possible that root module is built without `getTenantRootModule`.
This leads to a bug where child module requires externals, root module does not provide but its skipped validation.
Test suite and locally building changes into one-app.

fix(loadModule): missing getTenantRootModule

---

.github/workflows/set-tag.yml

create new action to set the dist tag for npm registy.
to fix incorrect tags in the npm registry

chore(workflow): set npm registry tag

---

.github/workflows/set-tag.yml

final tweaks to have workflow publish.

chore(workflow): set tag -remove from echo

---

packages/holocron/__tests__/loadModule.node.spec.js
packages/holocron/src/externalRegistry.js
packages/holocron/src/loadModule.node.js
packages/holocron/src/loadModule.web.js

Use separate browser and node integrity values for loading fallback externals.
Prevent modules from being loaded when external fallbacks are required and missing integrity values.
Locally using packed holocron installed into one app with local modules requiring externals

fix(externals): use browser and node integrity values

---

packages/holocron/__tests__/loadModule.node.spec.js
packages/holocron/src/loadModule.node.js

`Holocron.loadModule.node` was registering all fallbacks when only missing fallbacks needed to be registered. 
Ensure that only required fallbacks are loaded for a module.
Unit tests

fix(loadModule): only register required fallbacks

---

.github/workflows/health-check.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
package.json
packages/holocron-module-register-webpack-plugin/__tests__/HolocronModuleRegisterPlugin.spec.js

Drop support for Node 16 as its EOL
Do not support dead versions of Node
N/A

chore(node): drop 16 support as EOL

---

packages/holocron-module-register-webpack-plugin/CHANGELOG.md
packages/holocron-module-register-webpack-plugin/package.json
packages/holocron-module-route/CHANGELOG.md
packages/holocron-module-route/package.json
packages/holocron/CHANGELOG.md
packages/holocron/package.json

- holocron-module-register-webpack-plugin@3.0.0-alpha.0
- holocron-module-route@2.0.0-alpha.0
- holocron@2.0.0-alpha.0

premajor alpha.0 releases for holocron packages

---

packages/holocron/package.json

move redux and react-redux to peer dependencies.

chore(redux): move to redux and react-redux to peer deps

---

packages/holocron/package.json
yarn.lock

This partially reverts 19d075578e129e2c1affccc9c3da18e815c3f5fa which make redux and react-redux peer deps.
making redux and react redux peer deps should have been done as a breaking change.

revert(holocron): redux react-redux peer deps

---

package.json
packages/holocron-module-route/package.json
packages/holocron/__tests__/__snapshots__/moduleRegistry.spec.js.snap
packages/holocron/__tests__/__snapshots__/updateModuleRegistry.spec.js.snap
packages/holocron/__tests__/holocronModule.spec.jsx
packages/holocron/package.json
packages/holocron/src/createHolocronStore.js
yarn.lock

BREAKING CHANGES: major version requirements to react redux and react redux
This moves redux and react-redux to peer deps.
requires react >18.2.0
requires redux >=5
requires react-redux >=9

feat(deps): major update react, redux, react-redux, redux-thunk
